version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-server
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
    ports:
      - "9092:9092"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
